"""add column for about me

Revision ID: 975ef94c324c
Revises: e729ab2a4e28
Create Date: 2020-07-21 12:37:01.332378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975ef94c324c'
down_revision = 'e729ab2a4e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
